# -*- coding: utf-8 -*-
"""week2-Connected_components.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1on93Oufy4kFIz-hKl4B1F2pWa735Rm7H
"""

!wget https://github.com/Alireza-Akhavan/SRU-deep-1402/blob/master/images/persian-digits.jpg?raw=true

!mv persian-digits.jpg?raw=true persian-digits.jpg

import cv2
import numpy as np
import matplotlib.pyplot as plt

# Read the input image (make sure it's a binary image)
image = cv2.imread('persian-digits.jpg', cv2.IMREAD_GRAYSCALE)
# Apply thresholding to create a binary image
_, binary_image = cv2.threshold(image, 128, 255, cv2.THRESH_BINARY)

binary_image = 255-binary_image

# Use connectedComponentsWithStats to obtain labels and bounding boxes
num_labels, labels, stats, centroids = cv2.connectedComponentsWithStats(binary_image, connectivity=8)

# Iterate through each connected component
for label in range(1, num_labels):
    # Get the bounding box of the current connected component
    x, y, w, h = stats[label][:4]

    # Crop the connected component using the bounding box
    connected_component = binary_image[y:y+h, x:x+w]
    if w>5 and h>5:
      plt.figure()
      plt.imshow(connected_component, cmap='gray')

